name: helm-chart-releaser

on:
  push:
    branches:
      - master

jobs:
  helm-installer:
    runs-on: ubuntu-latest
    steps:
    # - name: install_dependencies
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build &push
      #uses: docker/build-push-action@v2
      run: |
        docker build . -f build/Dockerfile -t thunderdome:latest
        docker tag thunderdome:latest codesameer/thunderdome:latest 
        docker push codesameer/thunderdome:latest
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.1
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.4.0
      env:
        CR_TOKEN: "${{ secrets.CR2_TOKEN }}"
      
